version: '3.8'

services:
  backend:
    build:
      context: . 
    restart: always
    depends_on:
      - proxy
    secrets:
      - RDS_CONNECTION_STRING
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - ConnectionStrings__DefaultConnection=file:/run/secrets/rds_connection_string

  proxy:
    image: nginx:latest
    ports:
      - 80:80
    depends_on: 
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db-data:
