version: '3.8'

services:
  backend:
    image: backend_image
    depends_on:
      - proxy
    secrets:
      - rds_connection_string
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - ConnectionStrings__DefaultConnection=file:/run/secrets/rds_connection_string

  proxy:
    image: nginx:latest
    ports:
      - 80:80
    depends_on: 
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

secrets:
    rds_connection_string:
      external: true